name: EasyGroceries
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get:
  device_preview: 0.4.7
  auto_size_text: ^2.1.0
  lottie: ^0.7.0+1
  localstorage: ^3.0.0
  flutter_spinkit: '^4.1.2'
  flutter_launcher_icons: '^0.8.0'
  flutter_swiper: ^1.1.6
  url_launcher: ^5.7.10
  intl: ^0.16.1
  image_picker: ^0.6.7+14
  path_provider: ^1.6.24
  path: ^1.7.0
  flutter_svg: ^0.18.0
  firebase_auth: ^0.18.4+1
  google_sign_in: ^4.5.6
  firebase_database: ^4.4.0
  firebase_storage: ^5.2.0
  flutter_tags: '^0.4.9+1'
  flappy_search_bar: ^1.7.2
  audioplayers: ^0.12.0
  flutter_colorpicker: ^0.3.5

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/appIcon.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/sounds/
