name: foodz
description: A new Flutter project.

version: 1.0.0+3

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get: 4.1.1
  auto_size_text: ^2.1.0
  lottie: ^0.7.0+1
  shared_preferences: 2.0.5
  flutter_spinkit: '^4.1.2'
  flutter_launcher_icons: '^0.8.0'
  flutter_swiper: ^1.1.6
  url_launcher: ^6.0.3
  intl: ^0.17.0
  image_picker: ^0.7.4
  path_provider: ^2.0.1
  path: ^1.7.0
  flutter_svg: ^0.18.0
  firebase_auth: ^1.0.1
  google_sign_in: ^4.5.6
  firebase_database: ^6.1.1
  flutter_tags: '^0.4.9+1'
  flutter_colorpicker: ^0.3.5
  share: ^0.6.5+4
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.1
  firebase_dynamic_links: ^0.8.0
  cloud_firestore: ^1.0.3
  flutter_search_bar: ^2.1.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/appIcon.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/sounds/
